---
- hosts: localhost
  vars:
    the_user: "chobe"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - import_tasks: tasks/core.yml
    - import_tasks: tasks/git.yml
    - import_tasks: tasks/personal-projects.yml
    - import_tasks: tasks/zsh.yml
...
