---
- name: Install Systems Packages
  become: true
  package:
    name:
      - "curl"
      - "git"
      - "htop"
      - "zsh"
      - "python3-pip"
      - "compton"
      - "moreutils"
      - "apt-transport-https"
      - "build-essential"
      - "cmake"
      - "pkg-config"
  tags:
    - install
    - core
...
