---
- name: Install Systems Packages
  become: true
  package:
    name:
      - "curl"
      - "git"
      - "htop"
      - "zsh"
      - "python3-pip"
      - "compton"
      - "moreutils"
      - "apt-transport-https"
      - "build-essential"
      - "cmake"
      - "pkg-config"
      - "tmux"
      - "fzf"
      - "i3"
      - "dconf-editor"
  tags:
    - install
    - core

- name: dconf i3
  shell: dconf write /org/mate/desktop/session/required-components/windowmanager "'i3'"
  tags:
    - install
    - core

- name: dconf i3
  shell: dconf write /org/mate/desktop/background/show-desktop-icons "false"
  tags:
    - install
    - core
...
