- name: Installing stow
  become: true
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow

- name: Stow dotfiles
  become_user: chobe
  shell: cd $HOME/personal/dotfiles/main && ./install
  tags:
    - install
    - dotfiles
    - stow
