- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "soy_chobe@yahoo.com"
  tags:
    - install
    - core
    - git

- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "chobe"
  tags:
    - install
    - core
    - git

- name: Git config default branch
  git_config:
    name: init.defaultBranch
    scope: global
    value: "main"
  tags:
    - install
    - core
    - git
