- name: Dotfiles exists
  stat:
    path: "{{ personal }}/dotfiles"
  register: dotfiles
  tags:
    - install
    - dotfiles
    - personal-project

- name: Personal Project Dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:chobe/dotfiles.git'
    dest: "{{ personal }}/dotfiles"
  tags:
    - install
    - dotfiles
    - personal-project
  when: dotfiles.stat.exists == False

- name: Chobe exists
  stat:
    path: "{{ personal }}/chobe"
  register: chobe
  tags:
    - install
    - chobe
    - personal-project

- name: Personal Project Chobe
  ansible.builtin.git:
    repo: 'git@github.com:chobe/chobe.git'
    dest: "{{ personal }}/chobe"
  tags:
    - install
    - chobe
    - personal-project
  when: chobe.stat.exists == False

- name: Setup exists
  stat:
    path: "{{ personal }}/workstation-setup"
  register: setup
  tags:
    - install
    - setup
    - personal-project

- name: Personal Project Setup
  ansible.builtin.git:
    repo: 'git@github.com:chobe/workstation-setup.git'
    dest: "{{ personal }}/workstation-setup"
  tags:
    - install
    - setup
    - personal-project
  when: setup.stat.exists == False

- name: Hogar exists
  stat:
    path: "{{ personal }}/hogar.gt"
  register: hogar
  tags:
    - install
    - hogar
    - personal-project

- name: Personal Project Hogar
  ansible.builtin.git:
    repo: 'git@github.com:hogargt/hogar.gt.git'
    dest: "{{ personal }}/hogar.gt"
  tags:
    - install
    - hogar
    - personal-project
  when: hogar.stat.exists == False

- name: SiteKit exists
  stat:
    path: "{{ personal }}/sitekit.gt"
  register: sitekit
  tags:
    - install
    - sitekit
    - personal-project

- name: Personal Project SiteKit
  ansible.builtin.git:
    repo: 'git@github.com:chobe/sitekit.git'
    dest: "{{ personal }}/sitekit"
  tags:
    - install
    - sitekit
    - personal-project
  when: sitekit.stat.exists == False
