---
- name: Change shell to zsh
  become: true
  shell: usermod --shell /bin/zsh {{ the_user }}
  tags: &tags_for_zsh [ 'install', 'dotfiles', 'zsh']

- name: Check that the somefile.conf exists
  stat:
    path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
  register: oh_my_stats
  tags: *tags_for_zsh

- name: Download Oh-My-Zsh
  get_url:
    url: https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: ~/install-oh-my-zsh.sh
    mode: '0777'
  tags: *tags_for_zsh
  when: oh_my_stats.stat.exists == False
  become_user: chobe

- name: Install Oh-My-Zsh
  shell: ~/install-oh-my-zsh.sh
  tags: *tags_for_zsh
  when: oh_my_stats.stat.exists == False
  become_user: chobe

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags: *tags_for_zsh

- name: Install passion theme
  get_url:
    url: https://raw.githubusercontent.com/ChesterYue/ohmyzsh-theme-passion/master/passion.zsh-theme
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/themes"
  tags: *tags_for_zsh
